name: 'GitHub ZKS Robot'

on:
  push:
    branches:
      - master

jobs:
  zks-emailbot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: 'Set up Python'
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: 'Install requirements'
        run: pip install -r ./requirements.txt
      - name: 'Working'
        export sprice=1.5
        export bprice=1.8
        run: python ./main.py ${{ secrets.MAIL_USERNAME }} ${{ secrets.MAIL_PASSWORD }} ${{ secrets.RECEIVER }} $sprice $bprice