name: 'GitHub ZKS Robot'

on:
  schedule:
    - cron:  '*/6 * * * *'

jobs:
  zks-emailbot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: 'Set up Python'
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: 'Install requirements'
        run: pip install -r ./requirements.txt
      - name: 'Working'
        run: bash ./main.sh
      - name: 'Send mail'
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.163.com
          server_port: 465
          username: ${{ secrets.MAIL_USERNAME }}
          password: ${{ secrets.MAIL_PASSWORD }}
          subject: CSDN Report
          body: file://email.txt
          to: ${{ secrets.RECEIVER }}
          from: GitHub Actions